# Generated by Django 3.2.3 on 2021-06-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('number_of_events', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('service_type', models.CharField(choices=[('catering', 'Catering'), ('decoration', 'Decoration'), ('Photo and Videography', 'Photo and Videography'), ('VIP Transport', 'VIP Transport')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('license_id', models.CharField(max_length=20)),
                ('isApproved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('cost', models.FloatField()),
                ('isAvailable', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('marriage', 'marriage'), ('birthday', 'birthday'), ('techfest', 'techfest'), ('exhibition', 'exhibition'), ('seminar', 'seminar'), ('conference', 'conference')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=12)),
                ('totalServices', models.IntegerField(default=0)),
                ('service_1', models.CharField(choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photo and Videography', 'Photo and Videography'), ('VIP Transport', 'VIP Transport')], default='Catering', max_length=60)),
                ('service_2', models.CharField(blank=True, choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photo and Videography', 'Photo and Videography'), ('VIP Transport', 'VIP Transport')], max_length=60, null=True)),
                ('service_3', models.CharField(blank=True, choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photo and Videography', 'Photo and Videography'), ('VIP Transport', 'VIP Transport')], max_length=60, null=True)),
                ('service_4', models.CharField(blank=True, choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photo and Videography', 'Photo and Videography'), ('VIP Transport', 'VIP Transport')], max_length=60, null=True)),
                ('numberOfVIPs', models.IntegerField(default=0)),
                ('isApproved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.customer_detail')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.venue')),
            ],
        ),
    ]
