# Generated by Django 3.2.3 on 2021-06-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP_Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_vehicles', models.IntegerField()),
                ('vehicle_1', models.CharField(max_length=50)),
                ('charge_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_2', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_3', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_4', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_n_Videography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_equipments', models.IntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_1', models.CharField(max_length=50)),
                ('price_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_item_2', models.CharField(blank=True, max_length=50, null=True)),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_item_3', models.CharField(blank=True, max_length=50, null=True)),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_item_4', models.CharField(blank=True, max_length=50, null=True)),
                ('price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.service_company')),
            ],
        ),
    ]
